### ISSUE TITLE
老师，为什么加入正则化防止过拟合之后准确率降低了？

### ISSUE THREAD

**Issue by hakunacc** [mousecpn/MachineLearning_HW_CQUT#3]
原使用的网络如下：
 def __init__(self):
        super(Net,self).__init__()
        self.conv1 = nn.Conv2d(1, 16, kernel_size=5)
        self.conv2 = nn.Conv2d(16, 32, kernel_size=5)
        self.mp = nn.MaxPool2d(2)
        self.relu = nn.ReLU()
        self.fc1 = nn.Linear(120,84)
        self.fc2 = nn.Linear(84,10)
        self.logsoftmax = nn.LogSoftmax()
        
    def forward(self,x):
        in_size = x.size(0)
        out = self.relu(self.mp(self.conv1(x)))
        out = self.relu(self.conv2(out))
        out = out.view(in_size, -1)
        out = self.relu(self.fc1(out))
        out = self.fc2(out)
        return self.logsoftmax(out)
准确率为：0.9756，查看损失函数发现如图所示中间出现过拟合现象，因此在优化器中加入weight_decay=1e-5指定权值衰减率。从图像上看，过拟合现象有好转，但是精确度却略有下降0.9728。请问这是正常情况吗
<img width="290" alt="图片1" src="https://user-images.githubusercontent.com/92583451/140651179-c718b512-8960-4a21-911b-85719872e46c.png">
<img width="319" alt="图片2" src="https://user-images.githubusercontent.com/92583451/140651228-6a8d47e6-f45c-4598-8ab3-95421dcd9d9b.png">

**Comment by mousecpn** [comment]
> 原使用的网络如下： def **init**(self): super(Net,self).**init**() self.conv1 = nn.Conv2d(1, 16, kernel_size=5) self.conv2 = nn.Conv2d(16, 32, kernel_size=5) self.mp = nn.MaxPool2d(2) self.relu = nn.ReLU() self.fc1 = nn.Linear(120,84) self.fc2 = nn.Linear(84,10) self.logsoftmax = nn.LogSoftmax()
> 
> ```
> def forward(self,x):
>     in_size = x.size(0)
>     out = self.relu(self.mp(self.conv1(x)))
>     out = self.relu(self.conv2(out))
>     out = out.view(in_size, -1)
>     out = self.relu(self.fc1(out))
>     out = self.fc2(out)
>     return self.logsoftmax(out)
> ```
> 
> 准确率为：0.9756，查看损失函数发现如图所示中间出现过拟合现象，因此在优化器中加入weight_decay=1e-5指定权值衰减率。从图像上看，过拟合现象有好转，但是精确度却略有下降0.9728。请问这是正常情况吗 <img alt="图片1" width="290" src="https://user-images.githubusercontent.com/92583451/140651179-c718b512-8960-4a21-911b-85719872e46c.png"> <img alt="图片2" width="319" src="https://user-images.githubusercontent.com/92583451/140651228-6a8d47e6-f45c-4598-8ab3-95421dcd9d9b.png">

老实说从图像看也看不出过拟合有所好转······也不知道你打印的是训练loss还是验证集loss，如果代码没改打印的就是训练集的loss。
正则化参数是要调的，并没有绝对说加入正则化一定会保证不过拟合，如果加了正则化性能下降了，那就不加呗。

**Comment by hakunacc** [comment]
好嘞，谢谢老师，我再调一调！

**Comment by hakunacc** [comment]
好嘞！谢谢老师。最后没有一直揪着过拟合这个问题，而是改了其他参数，准确率确实提升了不少
